POST http://localhost:3000/class HTTP/1.1
content-type: application/json

{
    "name": "Data Structures And Algorithms",
    "duration": "200"
}
        
###

POST http://localhost:3000/class HTTP/1.1
content-type: application/json

{
    "name": "TypeOrm Migrations and Models",
    "duration": "60"
}
        