//The 1 on the route is the clientId - will fail if !clientId
POST http://localhost:8080/api/client/1/transaction HTTP/1.1
content-type: application/json

{
    "amount": 500,
    "type": "deposit"
}

###

POST http://localhost:8080/api/client/3/transaction HTTP/1.1
content-type: application/json

{
    "amount": 10,
    "type": "withdraw"
}

###


POST http://localhost:8080/api/client/2/transaction HTTP/1.1
content-type: application/json

{
    "amount": 10.00,
    "type": "withdraw"
}

###