###
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Ezra",
    "lastName": "Cunningham"
}
###
GET http://localhost:3000/users/ HTTP/1.1

###
GET http://localhost:3000/users/14 HTTP/1.1


###
DELETE http://localhost:3000/users/banana HTTP/1.1
content-type: application/json

###
PUT http://localhost:3000/users/16 HTTP/1.1
content-type: application/json

{
    "firstName": "Pedro",
    "lastName": "Martinez"
}