//get client information
GET http://localhost:8080/api/client/1/clientInfo HTTP/1.1
content-type: application/json

###
//get client transactions
GET http://localhost:8080/api/client/1/clientTransactions HTTP/1.1
content-type: application/json

###